#!/bin/bash

while [[ True ]]; do
        charge="$($HOME/.mycmds/battery | rev | cut -c2- | rev)"
        state="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | cut -d ' ' -f 20)"
	
	if [[ $charge -le 20 ]] && [[ $state = "discharging" ]]; then
		notify-send "Low Battery @_@" "Battery is $charge%"
	fi
	sleep 200
done
